# 1. Komendy

sns.kdeplot(data[:,0], data[:,1],n_levels=10, cmap="viridis_r", ax = ax3, bw = 1) 

sns.distplot(data[:,0], ax = ax1, bins = bins)

plt.quiver(*[B,0],*[0,A], scale = scale, width = .01,  color = "cornflowerblue", label = r"A: $\sqrt{var[x]}$")


Matrix(np.corrcoef(A[:,0],A[:,1]))

<code>np.intertools.product(range(12),range(7))</code>

np.std()
np.mean()
np.var()
np.cov()
np.linalg.norm()
- <code> gauss = lambda x,m,t: (1/(np.sqrt(2*np.pi*t**2)))*np.exp(-(x-m)**2/(2*t**2))</code>
- <code>plt.hist(currData[:,0],50) </code> -> juz gotowe
- <code>p.einsum('...k,kl,...l->...', pos-m, Sinv, pos-m) </code> -> einstein sum
- <code>ax = fig.add_subplot(gs[1,0], projection='3d')</code>
- <code>plt.plot(x,stats.norm.pdf(x,meanX,np.sqrt(cov[:,0][0])), c = "k", lw = 3);</code>
- <code>X,Y = np.meshgrid(linspace,linspace)</code> - Przydaje sie do plaszczyzn ciaglych
- <code>ax.contour3D(X,Y,Z, levels = 100, alpha = .2, cmap = "binary_r")
<br>ax.contour(X,Y,Z, levels = 50, zdir='x')</code>
<br>rysowanie kontorow bez kdplota
- <code>Yevents = np.vstack(np.unique(events[:,1],return_counts=True)).T
<br>Xevents = np.hstack([Xevents,np.vstack([i/sum(Xevents[:,1]) for i in Xevents[:,1]])]) </code>
- <code>ys = stats.norm.pdf(x,mu,var)</code>
- <code> [plt.bar(x,binom.pmf(x,N,means[i]), alpha = .5) for i in range(0,3)] </code> --> kilka rodzajow barow na jednym bar-charcie

# 2. Notatki

1. events -> event space:               p,d,d,d,p,d,p,p... -> [p d] 
2. event space -> sample space:         [d p] ->  [dp pd dd pp]
3. sample space -> random variable:     [pp dp pd dd] -> [2 1 1 0] 
4. random variable  -> target space=    [2 1 1 0] -> [2 1 0]
5. random variable -> probability fun.: [2 1 1 0] -> [0.09 0.21 0.21 0.14] -> [0.9 0.42 0.14]

- rozne rodzaje wariancji -> rospisac i rozroznic. (Definition 6.9)
<br>standard v., raw-score v.,pairwise difference v.
- macierz kowariancji (co jest czym) (6.4.4)
-> jak warancje, tylko zamiast mnozyc X*X, jest X*Y
-> jest kilka ssposob -rozpicsz

- macierze korelacji 
$\rho_{X,Y}=\frac{cov(X,Y)}{\sqrt{\sigma(X)\sigma(Y)}}$
 
- independence (Def. 6.10) 
<br>- gdy p(x,y) = p(x)*(py) 
<br>- gdy P(A|B)=P(A) 
<br>- covariance = np.mean(XY)-nmean(X)*np.mean(Y)
<br>-Inpdependent and identically discibuted
<br>-conditional independence ((Def. 6.11)<br>
$X \perp \!\!\! \perp  Y | Z$ given $Z$, iff $p(x,y|z) = p(x|z)p(y|z)  \forall  z  \in Z$  where Z is the set of states of random variable Z
<br>-jeszcze doczytaj te rzeczy

- Gaussian distribution
<br>- podzial na pdf i inne
<br>- multivar gaus -> einstein sum
- podsumowujac:
<br>-wariancja, covariancja, corelacja


- Marginals and Conditionals of Gaussians (are gaussians)
<br>-odrotnosc z wariancji to tez odwrotnosc z homocovariancji?...
<br>-to jeszcze troche doczytaj
<br>*(a) Bivariate Gaussian;  <br>(b) marginal of a joint Gaussian distribution is Gaussian; <br>(c) the conditional distribution of a Gaussian is also Gaussian.*

- Conjugacy and the exponential Family
<br>-Bernoulli Distribution
<br>-Binomial Distribution
<br>-Beta Distribution
<br>-Beta-Binomial Binomial Conjugacy
<br>-Beta Bernouli Conjugacy
<br>
<code>
<br>scipy.stats.binom.ppf(0.01,N,means[0])
<br>scipy.stats.beta.pdf(xs,ab[0][0],ab[0][1])</code>
<br>*sprawdz parametry do tego*
<br><br> Bernoulli<br>
$$
p(x|\mu) = \mu^x(1-\mu)^{1-x};
\newline \mathbb{E}[x] = \mu, \mathbb{V}[x] = \mu(1-\mu)
$$
<br>Binomial<br>
$$
p(m|N,\mu) = {N\choose m}\mu^m(1-\mu)^{N-m}
\newline \mathbb{E}[m] = N\mu, \mathbb{V}[m] = N\mu(1-\mu)
$$

- Change of Variables/Inverse Transfrom
<br>-Distribution Function Technique
<br>-Change of Variables Technique
<code>
<br>x = Symbol('x');  f = 3*x**2
<br>fLam = lambdify('x',f) 
<br>diff(Fy)
</code>

<font color='red'>Wez te notatki jako zbierz:</font>


1. Aditional resources:
<a href=http://www.zstatistics.com/videos#/distributions>ZED Statistic</a>

Univariate Gaussian equation:
$$
\ y_{u,\sigma}(x)=\frac{1}{\sigma \sqrt{2\pi}}exp^{\frac{-(x-u)^2}{2\sigma^2}}
$$
$$
y=\frac{1}{\sqrt{2\pi t^2}}e^{\frac{-(x-m)^2}{2t^2}}
$$

Given the multivariate Gaussian equation,
$$
p(x|\mu,\sigma^2) = \frac{e^{\frac{1}{2}(x-\mu)^T\Sigma^{-1}(x-\mu)}}{\sqrt{(2\pi)^D |\Sigma|}}
$$

$$
p(x|y) = N(\mu_{x|y},\Sigma_{x|y}) \\
\mu_{x|y} = \mu_x + \Sigma_{xy}\Sigma^{-1}_{yy}(y-\mu_y) \\
\Sigma_{x|y} = \Sigma_{xx} - \Sigma_{xy}\Sigma_{yy}^{-1}\Sigma_{yx}
$$

# 3. Exercieses




In [99]:
# 1. Conditional Vs Marginal probability

import numpy as np
import itertools
import pandas

BD=np.array(
    [[0.01, 0.02, 0.03, 0.1, 0.1],
    [0.05, 0.1, 0.05, 0.07, 0.2],
    [0.1, 0.05, 0.03, 0.05, 0.04]])
# BDdf=pandas.DataFrame(data=BD,columns=['A,B,C,D,E'])

print(BD)

# marginal probability -> suma calego wierszaLUBcolumny / wszystkie sample -> podzbior / caly zbior
Px=[np.sum(BD[:,i])/BD.size for i in np.arange(BD.shape[1])]    # suma kolumn/N
Py=[np.sum(BD[i,:])/BD.size for i in np.arange(BD.shape[0])]    # suma wiersza/N

# conditional probability  ->  sampl / podzbior (* podzbior dotyczy warunku) -> sample / suma wierwsza/columny  
Pxoy=np.zeros(shape=BD.shape)
Pyox=np.zeros(shape=BD.shape)
for i,j in itertools.product( range(BD.shape[0]) , range(BD.shape[1]) ):
    Pxoy[i,j]=BD[i,j]/np.sum(BD[i,:])   # sampl/suma wiersza
    Pyox[i,j]=BD[i,j]/np.sum(BD[:,j])      # sampl/suma kolumny
Pxoy,Pyox


# test = [[(i+1)*(j+1) for j in range(5)] for i in range(4)]
# print(test)

# alternatywnie
Pxoy2=np.array([[j/np.sum(BD[i,:]) for j in BD[i,:]] for i in range(BD.shape[0])])
Pyox2=np.array([[j/np.sum(BD[:,i]) for j in BD[:,i]] for i in range(BD.shape[1])]).T

print(Pxoy)
print(Pxoy2)
print(Pyox)
print(Pyox2)


[[0.01 0.02 0.03 0.1  0.1 ]
 [0.05 0.1  0.05 0.07 0.2 ]
 [0.1  0.05 0.03 0.05 0.04]]
[[0.03846154 0.07692308 0.11538462 0.38461538 0.38461538]
 [0.10638298 0.21276596 0.10638298 0.14893617 0.42553191]
 [0.37037037 0.18518519 0.11111111 0.18518519 0.14814815]]
[[0.03846154 0.07692308 0.11538462 0.38461538 0.38461538]
 [0.10638298 0.21276596 0.10638298 0.14893617 0.42553191]
 [0.37037037 0.18518519 0.11111111 0.18518519 0.14814815]]
[[0.0625     0.11764706 0.27272727 0.45454545 0.29411765]
 [0.3125     0.58823529 0.45454545 0.31818182 0.58823529]
 [0.625      0.29411765 0.27272727 0.22727273 0.11764706]]
[[0.0625     0.11764706 0.27272727 0.45454545 0.29411765]
 [0.3125     0.58823529 0.45454545 0.31818182 0.58823529]
 [0.625      0.29411765 0.27272727 0.22727273 0.11764706]]


In [ ]:
# 2. 